### ISSUE TITLE
Icalendar import is broken

### ISSUE THREAD

**Issue by thet** [plone/plone.app.event#214] opened 2016-03-02 20:19 UTC
With plone.app.event 2.x on Plone 5.0, if you click on a folder on actions>enable ical import, you will get an "This page does not seem to exist…" error.
You can do an ical import by visiting "@@ical_import_settings" directly.

Needs fixing.

**Comment by gp54321** [comment] 2018-03-31 22:56
tested it with Plone 5.1.1 soft-released with fixes surely unrelated and there is no 'this page does not seem to exist'. I actually tested the import of an ical file. Did not work great (no support for 'Organizer') but it's a limitation not a bug. Issue should be closed IMO.

**Closed** 2022-08-24 15:33 UTC
Labels: 01 type: bug, 13 prio: normal, 42 lvl: moderate
